#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'

PS1='[\u@\h \W]\$ '

# Aliases

alias ll="ls -l"
alias s="sudo"
alias k="kubectl"
alias z="zellij"
alias lz="lazygit"
alias ld="lazydocker"
alias b="btop --tty_on"
alias vpn="/home/fabioc/Documents/scripts/allScripts/vpn.sh"

# Programs

eval "$(mcfly init bash)"

# By Default open in Documents

cd $HOME/Documents

